### ISSUE TITLE
test nanny feature

### ISSUE THREAD

**Issue by inexplicable** [cubejs/cluster2#39]
nanny feature is to verify that all workers are responsive, we need a test case to verify when a worker failed to produce heartbeat over 3 mins, master will force a kill of this worker.

**Comment by zhuchenwang** [comment]
I already forked this repo and added code coverage report to branch cluster3. You can merge it back. BTW, the coverage tool seems not work correctly in cluster mode. For example, current test cases covers most of the emitter code. However, the report says only code in master has been executed.
